version: "3.8"

services:
  notification-api:
    build: .
    ports:
      - "3004:3004"
    env_file:
      - .env
    environment:
      PORT: 3004
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - shoong-network

networks:
  shoong-network:
    external: true